name: Walls
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  flutter_custom_clippers: ^1.1.1
  intro_views_flutter: ^2.8.1
  wave: ^0.0.8
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.7
  url_launcher_web: ^0.1.1+5
  dio: ^3.0.9
  shared_preferences: ^0.5.7+2
  random_string: ^2.0.1
  image_picker_saver: ^0.3.0
  permission: ^0.1.7
  permission_handler: ^4.2.0+hotfix.3
  bottomreveal: ^1.0.0
  charts_flutter: ^0.9.0
  animated_floatactionbuttons: ^0.1.0
  path_provider: ^1.6.7
  share: ^0.6.4+2
  intl: ^0.16.1
  flare_flutter: ^2.0.3
  rxdart: ^0.24.1
  rxdart_codemod: ^0.1.5
  flutter_bloc : ^4.0.0
  cached_network_image: ^2.2.0+1
  wallpaper: ^0.0.8
  package_info: ^0.4.0+18
  flutter_staggered_grid_view: ^0.3.0
  crop: ^0.3.1+1
  http: ^0.12.1
  image_gallery_saver: ^1.2.2
  firebase_database: ^3.1.5
  timeago: ^2.0.26
  firebase_core: ^0.4.4+3
  email_validator: ^1.0.4
  cloud_firestore:
  firebase_auth:
  firebase_messaging:
  flutter_local_notifications:
  firebase_admob:
  quick_actions: ^0.4.0+5
  full_screen_image: ^1.0.2
  launch_review: ^2.0.0
  in_app_purchase: ^0.3.4
  wiredash: ^0.1.0
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-medium.ttf
      - asset: assets/fonts/Raleway-semibold.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
